In [38]:
import torch
import numpy as np
x = torch.tensor([1, 2, 3], dtype=torch.float64)
X = torch.tensor(np.array([1, 2, 3]), dtype=torch.float64)

In [39]:
print(x.size())
print(X.size())

torch.Size([3])
torch.Size([3])


In [27]:
a = [1,2,3]
b = [4,5,6]
c= [7,8,9]
y = []
y.append(a)
y.append(b)
y.append(c)

In [58]:
check = []
check.append((1,2))
check.append((2,1))

In [59]:
np.array(check).T.shape

(2, 2)

In [56]:
check = []
check.extend([[1, 2], [2, 1]])
np.array(check).T.shape

(2, 2)

In [64]:
check = []
check.extend([[1, 2], [2, 1]])
np.array(check).T

array([[1, 2],
       [2, 1]])

In [66]:
np.array(check)

array([[1, 2],
       [2, 1]])

In [70]:
check = []
check.append([1, 2])
check.append([2, 1])
np.array(check)

array([[1, 2],
       [2, 1]])